services:
  billing:
    build:
      context: ./New_billing
      dockerfile: Dockerfile
    container_name: billing_app
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./New_billing:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./DATA_BASE:/DATA_BASE:ro


  control:
    build:
      context: ./New_Contol_plant
      dockerfile: Dockerfile
    container_name: control_app
    environment:
      - DISPLAY=host.docker.internal:0.0
      - IS_DOCKER=true
    volumes:
      - ./New_Contol_plant:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./DATA_BASE:/app/DATA_BASE


  report:
    build:
      context: ./New_report
      dockerfile: Dockerfile
    container_name: report_app
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ./New_report:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./DATA_BASE:/DATA_BASE