# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Report.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTreeWidget,
    QTreeWidgetItem, QWidget)

class Ui_Report(object):
    def setupUi(self, Report):
        if not Report.objectName():
            Report.setObjectName(u"Report")
        Report.resize(1550, 850)
        Report.setMinimumSize(QSize(1550, 850))
        Report.setMaximumSize(QSize(1550, 850))
        font = QFont()
        font.setFamilies([u"TH Niramit AS"])
        Report.setFont(font)
        Report.setLocale(QLocale(QLocale.Thai, QLocale.Thailand))
        self.centralwidget = QWidget(Report)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 2555, 851))
        self.tabWidget.setMinimumSize(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"TH Niramit AS"])
        font1.setPointSize(15)
        self.tabWidget.setFont(font1)
        self.tab_Order_history = QWidget()
        self.tab_Order_history.setObjectName(u"tab_Order_history")
        self.show_value_lineEdit = QLineEdit(self.tab_Order_history)
        self.show_value_lineEdit.setObjectName(u"show_value_lineEdit")
        self.show_value_lineEdit.setGeometry(QRect(230, 120, 281, 35))
        font2 = QFont()
        font2.setFamilies([u"TH Niramit AS"])
        font2.setPointSize(20)
        font2.setBold(True)
        self.show_value_lineEdit.setFont(font2)
        self.show_value_lineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.export_pushButton = QPushButton(self.tab_Order_history)
        self.export_pushButton.setObjectName(u"export_pushButton")
        self.export_pushButton.setGeometry(QRect(1100, 100, 151, 61))
        self.export_pushButton.setFont(font2)
        self.start_date_label = QLabel(self.tab_Order_history)
        self.start_date_label.setObjectName(u"start_date_label")
        self.start_date_label.setGeometry(QRect(30, 60, 91, 55))
        self.start_date_label.setFont(font2)
        self.select_date_label = QLabel(self.tab_Order_history)
        self.select_date_label.setObjectName(u"select_date_label")
        self.select_date_label.setGeometry(QRect(30, 10, 351, 55))
        self.select_date_label.setFont(font2)
        self.show_pushButton = QPushButton(self.tab_Order_history)
        self.show_pushButton.setObjectName(u"show_pushButton")
        self.show_pushButton.setGeometry(QRect(910, 100, 151, 61))
        self.show_pushButton.setFont(font2)
        self.end_date_label = QLabel(self.tab_Order_history)
        self.end_date_label.setObjectName(u"end_date_label")
        self.end_date_label.setGeometry(QRect(340, 60, 85, 55))
        self.end_date_label.setFont(font2)
        self.show_value_list_label = QLabel(self.tab_Order_history)
        self.show_value_list_label.setObjectName(u"show_value_list_label")
        self.show_value_list_label.setGeometry(QRect(530, 110, 131, 61))
        self.show_value_list_label.setFont(font2)
        self.show_value_label = QLabel(self.tab_Order_history)
        self.show_value_label.setObjectName(u"show_value_label")
        self.show_value_label.setGeometry(QRect(20, 110, 201, 61))
        self.show_value_label.setFont(font2)
        self.report_treeWidget = QTreeWidget(self.tab_Order_history)
        self.report_treeWidget.setObjectName(u"report_treeWidget")
        self.report_treeWidget.setGeometry(QRect(0, 180, 1550, 850))
        self.report_treeWidget.setMinimumSize(QSize(1550, 850))
        self.report_treeWidget.setMaximumSize(QSize(1550, 850))
        self.report_treeWidget.setFont(font2)
        self.report_treeWidget.setAutoExpandDelay(3)
        self.report_treeWidget.setSortingEnabled(False)
        self.report_treeWidget.header().setVisible(True)
        self.report_treeWidget.header().setCascadingSectionResizes(False)
        self.report_treeWidget.header().setMinimumSectionSize(50)
        self.report_treeWidget.header().setDefaultSectionSize(160)
        self.report_treeWidget.header().setHighlightSections(False)
        self.report_treeWidget.header().setProperty(u"showSortIndicator", False)
        self.report_treeWidget.header().setStretchLastSection(True)
        self.start_dateEdit = QDateEdit(self.tab_Order_history)
        self.start_dateEdit.setObjectName(u"start_dateEdit")
        self.start_dateEdit.setGeometry(QRect(160, 70, 141, 31))
        self.start_dateEdit.setCalendarPopup(True)
        self.end_dateEdit_2 = QDateEdit(self.tab_Order_history)
        self.end_dateEdit_2.setObjectName(u"end_dateEdit_2")
        self.end_dateEdit_2.setGeometry(QRect(440, 70, 141, 31))
        self.end_dateEdit_2.setCalendarPopup(True)
        self.tabWidget.addTab(self.tab_Order_history, "")
        self.tab_Stock = QWidget()
        self.tab_Stock.setObjectName(u"tab_Stock")
        self.groupBox = QGroupBox(self.tab_Stock)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 0, 1541, 791))
        font3 = QFont()
        font3.setFamilies([u"TH Niramit AS"])
        font3.setPointSize(18)
        self.groupBox.setFont(font3)
        self.rock1_label = QLabel(self.groupBox)
        self.rock1_label.setObjectName(u"rock1_label")
        self.rock1_label.setGeometry(QRect(140, 70, 81, 61))
        self.rock1_label.setFont(font3)
        self.rock1_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.rock1_input_weight_lineEdit.setObjectName(u"rock1_input_weight_lineEdit")
        self.rock1_input_weight_lineEdit.setGeometry(QRect(390, 60, 261, 61))
        self.rock1_left_kg_label = QLabel(self.groupBox)
        self.rock1_left_kg_label.setObjectName(u"rock1_left_kg_label")
        self.rock1_left_kg_label.setGeometry(QRect(1210, 80, 91, 61))
        self.rock1_left_kg_label.setFont(font3)
        self.rock1_input_kg_label = QLabel(self.groupBox)
        self.rock1_input_kg_label.setObjectName(u"rock1_input_kg_label")
        self.rock1_input_kg_label.setGeometry(QRect(660, 80, 91, 61))
        self.rock1_input_kg_label.setFont(font3)
        self.rock1_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.rock1_left_weight_lineEdit.setObjectName(u"rock1_left_weight_lineEdit")
        self.rock1_left_weight_lineEdit.setGeometry(QRect(940, 60, 261, 61))
        self.rock1_left_label = QLabel(self.groupBox)
        self.rock1_left_label.setObjectName(u"rock1_left_label")
        self.rock1_left_label.setGeometry(QRect(840, 70, 81, 61))
        self.rock1_left_label.setFont(font3)
        self.rock1_input_label = QLabel(self.groupBox)
        self.rock1_input_label.setObjectName(u"rock1_input_label")
        self.rock1_input_label.setGeometry(QRect(290, 70, 91, 61))
        self.rock1_input_label.setFont(font3)
        self.rock2_left_label = QLabel(self.groupBox)
        self.rock2_left_label.setObjectName(u"rock2_left_label")
        self.rock2_left_label.setGeometry(QRect(840, 170, 81, 61))
        self.rock2_left_label.setFont(font3)
        self.rock2_label = QLabel(self.groupBox)
        self.rock2_label.setObjectName(u"rock2_label")
        self.rock2_label.setGeometry(QRect(140, 170, 81, 61))
        self.rock2_label.setFont(font3)
        self.rock2_input_kg_label = QLabel(self.groupBox)
        self.rock2_input_kg_label.setObjectName(u"rock2_input_kg_label")
        self.rock2_input_kg_label.setGeometry(QRect(660, 180, 91, 61))
        self.rock2_input_kg_label.setFont(font3)
        self.rock2_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.rock2_input_weight_lineEdit.setObjectName(u"rock2_input_weight_lineEdit")
        self.rock2_input_weight_lineEdit.setGeometry(QRect(390, 160, 261, 61))
        self.rock2_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.rock2_left_weight_lineEdit.setObjectName(u"rock2_left_weight_lineEdit")
        self.rock2_left_weight_lineEdit.setGeometry(QRect(940, 160, 261, 61))
        self.rock2_left_kg_label = QLabel(self.groupBox)
        self.rock2_left_kg_label.setObjectName(u"rock2_left_kg_label")
        self.rock2_left_kg_label.setGeometry(QRect(1210, 180, 91, 61))
        self.rock2_left_kg_label.setFont(font3)
        self.rock2_input_label = QLabel(self.groupBox)
        self.rock2_input_label.setObjectName(u"rock2_input_label")
        self.rock2_input_label.setGeometry(QRect(290, 170, 91, 61))
        self.rock2_input_label.setFont(font3)
        self.sand_left_label = QLabel(self.groupBox)
        self.sand_left_label.setObjectName(u"sand_left_label")
        self.sand_left_label.setGeometry(QRect(840, 270, 81, 61))
        self.sand_left_label.setFont(font3)
        self.sand_label = QLabel(self.groupBox)
        self.sand_label.setObjectName(u"sand_label")
        self.sand_label.setGeometry(QRect(130, 260, 81, 61))
        self.sand_label.setFont(font3)
        self.sand_input_kg_label = QLabel(self.groupBox)
        self.sand_input_kg_label.setObjectName(u"sand_input_kg_label")
        self.sand_input_kg_label.setGeometry(QRect(660, 280, 91, 61))
        self.sand_input_kg_label.setFont(font3)
        self.sand_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.sand_input_weight_lineEdit.setObjectName(u"sand_input_weight_lineEdit")
        self.sand_input_weight_lineEdit.setGeometry(QRect(390, 260, 261, 61))
        self.sand_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.sand_left_weight_lineEdit.setObjectName(u"sand_left_weight_lineEdit")
        self.sand_left_weight_lineEdit.setGeometry(QRect(940, 260, 261, 61))
        self.sand_left_kg_label = QLabel(self.groupBox)
        self.sand_left_kg_label.setObjectName(u"sand_left_kg_label")
        self.sand_left_kg_label.setGeometry(QRect(1210, 280, 91, 61))
        self.sand_left_kg_label.setFont(font3)
        self.sand_input_label = QLabel(self.groupBox)
        self.sand_input_label.setObjectName(u"sand_input_label")
        self.sand_input_label.setGeometry(QRect(290, 260, 91, 61))
        self.sand_input_label.setFont(font3)
        self.fly_ash_left_label = QLabel(self.groupBox)
        self.fly_ash_left_label.setObjectName(u"fly_ash_left_label")
        self.fly_ash_left_label.setGeometry(QRect(840, 370, 81, 61))
        self.fly_ash_left_label.setFont(font3)
        self.fly_ash_label = QLabel(self.groupBox)
        self.fly_ash_label.setObjectName(u"fly_ash_label")
        self.fly_ash_label.setGeometry(QRect(120, 370, 81, 61))
        self.fly_ash_label.setFont(font3)
        self.fly_ash_input_kg_label = QLabel(self.groupBox)
        self.fly_ash_input_kg_label.setObjectName(u"fly_ash_input_kg_label")
        self.fly_ash_input_kg_label.setGeometry(QRect(660, 380, 91, 61))
        self.fly_ash_input_kg_label.setFont(font3)
        self.fly_ash_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.fly_ash_input_weight_lineEdit.setObjectName(u"fly_ash_input_weight_lineEdit")
        self.fly_ash_input_weight_lineEdit.setGeometry(QRect(390, 360, 261, 61))
        self.fly_ash_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.fly_ash_left_weight_lineEdit.setObjectName(u"fly_ash_left_weight_lineEdit")
        self.fly_ash_left_weight_lineEdit.setGeometry(QRect(940, 360, 261, 61))
        self.fly_ash_left_kg_label = QLabel(self.groupBox)
        self.fly_ash_left_kg_label.setObjectName(u"fly_ash_left_kg_label")
        self.fly_ash_left_kg_label.setGeometry(QRect(1210, 380, 91, 61))
        self.fly_ash_left_kg_label.setFont(font3)
        self.fly_ash_input_label = QLabel(self.groupBox)
        self.fly_ash_input_label.setObjectName(u"fly_ash_input_label")
        self.fly_ash_input_label.setGeometry(QRect(290, 370, 91, 61))
        self.fly_ash_input_label.setFont(font3)
        self.cement_left_label = QLabel(self.groupBox)
        self.cement_left_label.setObjectName(u"cement_left_label")
        self.cement_left_label.setGeometry(QRect(840, 470, 81, 61))
        self.cement_left_label.setFont(font3)
        self.cement_label = QLabel(self.groupBox)
        self.cement_label.setObjectName(u"cement_label")
        self.cement_label.setGeometry(QRect(140, 470, 51, 61))
        self.cement_label.setFont(font3)
        self.cement_input_kg_label = QLabel(self.groupBox)
        self.cement_input_kg_label.setObjectName(u"cement_input_kg_label")
        self.cement_input_kg_label.setGeometry(QRect(660, 480, 91, 61))
        self.cement_input_kg_label.setFont(font3)
        self.cement_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.cement_input_weight_lineEdit.setObjectName(u"cement_input_weight_lineEdit")
        self.cement_input_weight_lineEdit.setGeometry(QRect(390, 460, 261, 61))
        self.cement_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.cement_left_weight_lineEdit.setObjectName(u"cement_left_weight_lineEdit")
        self.cement_left_weight_lineEdit.setGeometry(QRect(940, 460, 261, 61))
        self.cement_left_kg_label = QLabel(self.groupBox)
        self.cement_left_kg_label.setObjectName(u"cement_left_kg_label")
        self.cement_left_kg_label.setGeometry(QRect(1210, 480, 91, 61))
        self.cement_left_kg_label.setFont(font3)
        self.cement_input_label = QLabel(self.groupBox)
        self.cement_input_label.setObjectName(u"cement_input_label")
        self.cement_input_label.setGeometry(QRect(290, 470, 91, 61))
        self.cement_input_label.setFont(font3)
        self.chemical_solution1_left_label = QLabel(self.groupBox)
        self.chemical_solution1_left_label.setObjectName(u"chemical_solution1_left_label")
        self.chemical_solution1_left_label.setGeometry(QRect(840, 570, 81, 61))
        self.chemical_solution1_left_label.setFont(font3)
        self.chemical_solution1_label = QLabel(self.groupBox)
        self.chemical_solution1_label.setObjectName(u"chemical_solution1_label")
        self.chemical_solution1_label.setGeometry(QRect(120, 570, 111, 61))
        self.chemical_solution1_label.setFont(font3)
        self.chemical_solution1_input_kg_label = QLabel(self.groupBox)
        self.chemical_solution1_input_kg_label.setObjectName(u"chemical_solution1_input_kg_label")
        self.chemical_solution1_input_kg_label.setGeometry(QRect(660, 580, 91, 61))
        self.chemical_solution1_input_kg_label.setFont(font3)
        self.chemical_solution1_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.chemical_solution1_input_weight_lineEdit.setObjectName(u"chemical_solution1_input_weight_lineEdit")
        self.chemical_solution1_input_weight_lineEdit.setGeometry(QRect(390, 560, 261, 61))
        self.chemical_solution1_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.chemical_solution1_left_weight_lineEdit.setObjectName(u"chemical_solution1_left_weight_lineEdit")
        self.chemical_solution1_left_weight_lineEdit.setGeometry(QRect(940, 560, 261, 61))
        self.chemical_solution1_left_kg_label = QLabel(self.groupBox)
        self.chemical_solution1_left_kg_label.setObjectName(u"chemical_solution1_left_kg_label")
        self.chemical_solution1_left_kg_label.setGeometry(QRect(1210, 580, 91, 61))
        self.chemical_solution1_left_kg_label.setFont(font3)
        self.chemical_solution1_input_label = QLabel(self.groupBox)
        self.chemical_solution1_input_label.setObjectName(u"chemical_solution1_input_label")
        self.chemical_solution1_input_label.setGeometry(QRect(290, 570, 91, 61))
        self.chemical_solution1_input_label.setFont(font3)
        self.chemical_solution2_left_label = QLabel(self.groupBox)
        self.chemical_solution2_left_label.setObjectName(u"chemical_solution2_left_label")
        self.chemical_solution2_left_label.setGeometry(QRect(840, 670, 81, 61))
        self.chemical_solution2_left_label.setFont(font3)
        self.chemical_solution2_label = QLabel(self.groupBox)
        self.chemical_solution2_label.setObjectName(u"chemical_solution2_label")
        self.chemical_solution2_label.setGeometry(QRect(110, 670, 131, 61))
        self.chemical_solution2_label.setFont(font3)
        self.chemical_solution2_input_kg_label = QLabel(self.groupBox)
        self.chemical_solution2_input_kg_label.setObjectName(u"chemical_solution2_input_kg_label")
        self.chemical_solution2_input_kg_label.setGeometry(QRect(660, 680, 91, 61))
        self.chemical_solution2_input_kg_label.setFont(font3)
        self.chemical_solution2_input_weight_lineEdit = QLineEdit(self.groupBox)
        self.chemical_solution2_input_weight_lineEdit.setObjectName(u"chemical_solution2_input_weight_lineEdit")
        self.chemical_solution2_input_weight_lineEdit.setGeometry(QRect(390, 660, 261, 61))
        self.chemical_solution2_left_weight_lineEdit = QLineEdit(self.groupBox)
        self.chemical_solution2_left_weight_lineEdit.setObjectName(u"chemical_solution2_left_weight_lineEdit")
        self.chemical_solution2_left_weight_lineEdit.setGeometry(QRect(940, 660, 261, 61))
        self.chemical_solution2_left_kg_label = QLabel(self.groupBox)
        self.chemical_solution2_left_kg_label.setObjectName(u"chemical_solution2_left_kg_label")
        self.chemical_solution2_left_kg_label.setGeometry(QRect(1210, 670, 91, 61))
        self.chemical_solution2_left_kg_label.setFont(font3)
        self.chemical_solution2_input_label = QLabel(self.groupBox)
        self.chemical_solution2_input_label.setObjectName(u"chemical_solution2_input_label")
        self.chemical_solution2_input_label.setGeometry(QRect(290, 670, 91, 61))
        self.chemical_solution2_input_label.setFont(font3)
        self.show_weight_pushButton = QPushButton(self.groupBox)
        self.show_weight_pushButton.setObjectName(u"show_weight_pushButton")
        self.show_weight_pushButton.setGeometry(QRect(1340, 60, 151, 61))
        self.show_weight_pushButton.setFont(font2)
        self.tabWidget.addTab(self.tab_Stock, "")
        Report.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Report)
        self.statusbar.setObjectName(u"statusbar")
        Report.setStatusBar(self.statusbar)

        self.retranslateUi(Report)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Report)
    # setupUi

    def retranslateUi(self, Report):
        Report.setWindowTitle(QCoreApplication.translate("Report", u"\u0e04\u0e2d\u0e19\u0e01\u0e23\u0e35\u0e15\u0e1c\u0e2a\u0e21 \u0e2b\u0e49\u0e32\u0e07\u0e2b\u0e38\u0e49\u0e19\u0e2a\u0e48\u0e27\u0e19\u0e08\u0e33\u0e01\u0e31\u0e14 \u0e1b\u0e32\u0e19\u0e02\u0e1b\u0e23\u0e34\u0e0d \u0e04\u0e2d\u0e19\u0e01\u0e23\u0e35\u0e15", None))
        self.export_pushButton.setText(QCoreApplication.translate("Report", u"\u0e2a\u0e48\u0e07\u0e04\u0e48\u0e32\u0e2d\u0e2d\u0e01", None))
        self.start_date_label.setText(QCoreApplication.translate("Report", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48\u0e40\u0e23\u0e34\u0e48\u0e21", None))
        self.select_date_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e25\u0e37\u0e2d\u0e01\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e41\u0e2a\u0e14\u0e07\u0e1c\u0e25", None))
        self.show_pushButton.setText(QCoreApplication.translate("Report", u"\u0e41\u0e2a\u0e14\u0e07\u0e1c\u0e25", None))
        self.end_date_label.setText(QCoreApplication.translate("Report", u"\u0e16\u0e36\u0e07\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48", None))
        self.show_value_list_label.setText(QCoreApplication.translate("Report", u"\u0e23\u0e32\u0e22\u0e01\u0e32\u0e23", None))
        self.show_value_label.setText(QCoreApplication.translate("Report", u"\u0e41\u0e2a\u0e14\u0e07\u0e04\u0e48\u0e32\u0e17\u0e31\u0e49\u0e07\u0e2b\u0e21\u0e14", None))
        ___qtreewidgetitem = self.report_treeWidget.headerItem()
        ___qtreewidgetitem.setText(9, QCoreApplication.translate("Report", u"\u0e04\u0e27\u0e32\u0e21\u0e1c\u0e34\u0e14\u0e1e\u0e25\u0e32\u0e14", None));
        ___qtreewidgetitem.setText(8, QCoreApplication.translate("Report", u"\u0e0a\u0e31\u0e48\u0e07\u0e08\u0e23\u0e34\u0e07", None));
        ___qtreewidgetitem.setText(7, QCoreApplication.translate("Report", u"\u0e04\u0e48\u0e32\u0e17\u0e35\u0e48\u0e01\u0e33\u0e2b\u0e19\u0e14", None));
        ___qtreewidgetitem.setText(6, QCoreApplication.translate("Report", u"\u0e2a\u0e48\u0e27\u0e19\u0e1c\u0e2a\u0e21", None));
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("Report", u"\u0e08\u0e33\u0e19\u0e27\u0e19", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("Report", u"\u0e27\u0e31\u0e19\u0e17\u0e35\u0e48 \u0e40\u0e27\u0e25\u0e32", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("Report", u"\u0e01\u0e33\u0e25\u0e31\u0e07\u0e2d\u0e31\u0e14", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("Report", u"\u0e23\u0e32\u0e22\u0e25\u0e30\u0e40\u0e2d\u0e35\u0e22\u0e14\u0e01\u0e32\u0e23\u0e2a\u0e48\u0e07\u0e2a\u0e34\u0e19\u0e04\u0e49\u0e32", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("Report", u"New Column", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("Report", u"\u0e25\u0e33\u0e14\u0e31\u0e1a", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Order_history), QCoreApplication.translate("Report", u"\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e2a\u0e31\u0e48\u0e07\u0e0b\u0e37\u0e49\u0e2d", None))
        self.groupBox.setTitle("")
        self.rock1_label.setText(QCoreApplication.translate("Report", u"\u0e2b\u0e34\u0e191", None))
        self.rock1_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.rock1_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.rock1_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.rock1_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.rock2_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.rock2_label.setText(QCoreApplication.translate("Report", u"\u0e2b\u0e34\u0e192", None))
        self.rock2_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.rock2_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.rock2_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.sand_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.sand_label.setText(QCoreApplication.translate("Report", u"\u0e17\u0e23\u0e32\u0e22", None))
        self.sand_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.sand_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.sand_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.fly_ash_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.fly_ash_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e16\u0e49\u0e32\u0e25\u0e2d\u0e22", None))
        self.fly_ash_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.fly_ash_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.fly_ash_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.cement_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.cement_label.setText(QCoreApplication.translate("Report", u"\u0e1b\u0e39\u0e19", None))
        self.cement_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.cement_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.cement_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.chemical_solution1_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.chemical_solution1_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e49\u0e33\u0e22\u0e32\u0e40\u0e04\u0e21\u0e351", None))
        self.chemical_solution1_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.chemical_solution1_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.chemical_solution1_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.chemical_solution2_left_label.setText(QCoreApplication.translate("Report", u"\u0e40\u0e2b\u0e25\u0e37\u0e2d", None))
        self.chemical_solution2_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e49\u0e33\u0e22\u0e32\u0e40\u0e04\u0e21\u0e352", None))
        self.chemical_solution2_input_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.chemical_solution2_left_kg_label.setText(QCoreApplication.translate("Report", u"kg.", None))
        self.chemical_solution2_input_label.setText(QCoreApplication.translate("Report", u"\u0e19\u0e33\u0e40\u0e02\u0e49\u0e32", None))
        self.show_weight_pushButton.setText(QCoreApplication.translate("Report", u"\u0e41\u0e2a\u0e14\u0e07\u0e1c\u0e25", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Stock), QCoreApplication.translate("Report", u"\u0e2a\u0e15\u0e47\u0e2d\u0e01\u0e2a\u0e34\u0e19\u0e04\u0e49\u0e32", None))
    # retranslateUi

